version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ~/Documents:/Documents:delegated
    restart: always

  php:
    build: ./php
    depends_on:
      - mysql
      - redis
    volumes:
      - ./php/custom.php.ini:/usr/local/etc/php/conf.d/docker-php-custom.ini
      - ~/Documents:/Documents:delegated
    restart: always

  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/custom.mysql.cnf:/etc/mysql/mysql.conf.d/custom.mysql.cnf
      - ./mysql/data:/var/lib/mysql
    restart: always

  redis:
    build: ./redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    restart: always

  portainer:
    build: ./portainer
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    restart: always

