version: "2"
services:
  nginx:
    depends_on:
      - php7
      - php8
    environment:
      - TZ=Asia/Shanghai
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ~/.acme.sh:/etc/nginx/.acme.sh
      - ~/Documents:/Documents:delegated

  php7:
    build: ./php7
    depends_on:
      - mariadb
      - redis
    environment:
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - ./php7/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ~/Documents:/Documents:delegated

  php8:
    build: ./php8
    depends_on:
      - mariadb
      - redis
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 9501:9501
    restart: always
    volumes:
      - ./php8/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ~/Documents:/Documents:delegated

  mariadb:
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_ROOT_PASSWORD=root
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mariadb/mysql:/var/lib/mysql

  redis:
    environment:
      - TZ=Asia/Shanghai
    image: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis/data:/data

  portainer:
    command: -H unix:///var/run/docker.sock
    image: portainer/portainer-ce
    ports:
      - 9443:9443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data

